name: Release using conventional commits on master

# ────────────────────────────────────────────────────
# 1) Give the built-in GITHUB_TOKEN write access to repo contents
# ────────────────────────────────────────────────────
permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # ────────────────────────────────────────────────────
      # 2) Checkout full history (so tags & commits can be read/pushed)
      # ────────────────────────────────────────────────────
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # ────────────────────────────────────────────────────
      # 3) Configure git user (so commits & tags carry an identity)
      # ────────────────────────────────────────────────────
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # ────────────────────────────────────────────────────
      # 4) Run the changelog action (it will now be able to push)
      # ────────────────────────────────────────────────────
      - name: Generate CHANGELOG & bump tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit: true
          push: true

      # ────────────────────────────────────────────────────
      # 5) Bump pubspec.yaml to match the new semver tag + build #
      # ────────────────────────────────────────────────────
      - name: Bump pubspec version
        if: steps.changelog.outputs.skipped == 'false'
        run: |
          TAG=${{ steps.changelog.outputs.tag }}      # e.g. "v1.2.3"
          VER=${TAG#v}                                # strips "v"
          sed -i "s/^version:.*/version: ${VER}+${GITHUB_RUN_NUMBER}/" pubspec.yaml
          git add pubspec.yaml
          git commit -m "chore: bump pubspec to ${VER}+${GITHUB_RUN_NUMBER}"
          git push

      # ────────────────────────────────────────────────────
      # 6) Build & release your Flutter APK
      # ────────────────────────────────────────────────────
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android release
        run: flutter build apk --release

      # 8) Create or update the GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.skipped == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:     ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body:         ${{ steps.changelog.outputs.clean_changelog }}
          draft:        false
          prerelease:   false

      # 9) Upload the APK as a release asset
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        if: steps.changelog.outputs.skipped == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        build/app/outputs/flutter-apk/app-release.apk
          asset_name:        app-release.apk
          asset_content_type: application/vnd.android.package-archive